[lint]
select = ["E", "F", "W", "C"]
ignore = ["W391", "E701"]
exclude = [
    "tests/*",  # Игнорировать тесты, если они есть
    "*.md",     # Игнорировать файлы markdown
    "*.pyi",    # Игнорировать файлы с типами аннотаций
    ".idea/*",  # Игнорировать конфигурации PyCharm
    ".ruff_cache/*",  # Игнорировать кэш линтера
    "venv/*",   # Игнорировать файлы в виртуальном окружении
]